// Mocks generated by Mockito 5.4.6 from annotations
// in mono_pos/test/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:mono_pos/core/common/result.dart' as _i6;
import 'package:mono_pos/core/services/sync/sync_service.dart' as _i2;
import 'package:mono_pos/data/datasources/interfaces/product_datasource.dart'
    as _i10;
import 'package:mono_pos/data/datasources/local/product_local_datasource_impl.dart'
    as _i4;
import 'package:mono_pos/data/models/product_model.dart' as _i7;
import 'package:mono_pos/data/models/product_unit_model.dart' as _i9;
import 'package:mono_pos/domain/entities/queued_action_entity.dart' as _i12;
import 'package:mono_pos/domain/repositories/queued_action_repository.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i2.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SyncMode get mode =>
      (super.noSuchMethod(
            Invocation.getter(#mode),
            returnValue: _i2.SyncMode.auto,
          )
          as _i2.SyncMode);

  @override
  bool get forcedOffline =>
      (super.noSuchMethod(Invocation.getter(#forcedOffline), returnValue: false)
          as bool);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setMode(_i2.SyncMode? mode) => super.noSuchMethod(
    Invocation.method(#setMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleMode() => super.noSuchMethod(
    Invocation.method(#toggleMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProductLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDatasourceImpl extends _i1.Mock
    implements _i4.ProductLocalDatasourceImpl {
  MockProductLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<int>> createProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [product]),
            returnValue: _i5.Future<_i6.Result<int>>.value(
              _i8.dummyValue<_i6.Result<int>>(
                this,
                Invocation.method(#createProduct, [product]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<int>>);

  @override
  _i5.Future<_i6.Result<void>> updateProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#updateProduct, [product]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<void>> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteProduct, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<_i7.ProductModel?>> getProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [id]),
            returnValue: _i5.Future<_i6.Result<_i7.ProductModel?>>.value(
              _i8.dummyValue<_i6.Result<_i7.ProductModel?>>(
                this,
                Invocation.method(#getProduct, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.ProductModel?>>);

  @override
  _i5.Future<_i6.Result<List<_i7.ProductModel>>> getAllUserProducts(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserProducts, [userId]),
            returnValue: _i5.Future<_i6.Result<List<_i7.ProductModel>>>.value(
              _i8.dummyValue<_i6.Result<List<_i7.ProductModel>>>(
                this,
                Invocation.method(#getAllUserProducts, [userId]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<List<_i7.ProductModel>>>);

  @override
  _i5.Future<_i6.Result<List<_i7.ProductModel>>> getUserProducts(
    String? userId, {
    String? orderBy = 'createdAt',
    String? sortBy = 'DESC',
    int? limit = 10,
    int? offset,
    String? contains,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserProducts,
              [userId],
              {
                #orderBy: orderBy,
                #sortBy: sortBy,
                #limit: limit,
                #offset: offset,
                #contains: contains,
              },
            ),
            returnValue: _i5.Future<_i6.Result<List<_i7.ProductModel>>>.value(
              _i8.dummyValue<_i6.Result<List<_i7.ProductModel>>>(
                this,
                Invocation.method(
                  #getUserProducts,
                  [userId],
                  {
                    #orderBy: orderBy,
                    #sortBy: sortBy,
                    #limit: limit,
                    #offset: offset,
                    #contains: contains,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i6.Result<List<_i7.ProductModel>>>);

  @override
  _i5.Future<_i6.Result<_i7.ProductModel?>> getProductByBarcode(
    String? barcode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductByBarcode, [barcode]),
            returnValue: _i5.Future<_i6.Result<_i7.ProductModel?>>.value(
              _i8.dummyValue<_i6.Result<_i7.ProductModel?>>(
                this,
                Invocation.method(#getProductByBarcode, [barcode]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.ProductModel?>>);

  @override
  _i5.Future<_i6.Result<void>> saveProductUnits(
    int? productId,
    List<_i9.ProductUnitModel>? units,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductUnits, [productId, units]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#saveProductUnits, [productId, units]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<List<_i9.ProductUnitModel>>> getProductUnits(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductUnits, [productId]),
            returnValue:
                _i5.Future<_i6.Result<List<_i9.ProductUnitModel>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i9.ProductUnitModel>>>(
                    this,
                    Invocation.method(#getProductUnits, [productId]),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i9.ProductUnitModel>>>);

  @override
  _i5.Future<_i6.Result<void>> deleteProductUnits(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductUnits, [productId]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteProductUnits, [productId]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);
}

/// A class which mocks [ProductDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDatasource extends _i1.Mock implements _i10.ProductDatasource {
  MockProductDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<int>> createProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [product]),
            returnValue: _i5.Future<_i6.Result<int>>.value(
              _i8.dummyValue<_i6.Result<int>>(
                this,
                Invocation.method(#createProduct, [product]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<int>>);

  @override
  _i5.Future<_i6.Result<void>> updateProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#updateProduct, [product]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<void>> deleteProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteProduct, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<_i7.ProductModel?>> getProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [id]),
            returnValue: _i5.Future<_i6.Result<_i7.ProductModel?>>.value(
              _i8.dummyValue<_i6.Result<_i7.ProductModel?>>(
                this,
                Invocation.method(#getProduct, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.ProductModel?>>);

  @override
  _i5.Future<_i6.Result<List<_i7.ProductModel>>> getAllUserProducts(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserProducts, [userId]),
            returnValue: _i5.Future<_i6.Result<List<_i7.ProductModel>>>.value(
              _i8.dummyValue<_i6.Result<List<_i7.ProductModel>>>(
                this,
                Invocation.method(#getAllUserProducts, [userId]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<List<_i7.ProductModel>>>);

  @override
  _i5.Future<_i6.Result<_i7.ProductModel?>> getProductByBarcode(
    String? barcode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductByBarcode, [barcode]),
            returnValue: _i5.Future<_i6.Result<_i7.ProductModel?>>.value(
              _i8.dummyValue<_i6.Result<_i7.ProductModel?>>(
                this,
                Invocation.method(#getProductByBarcode, [barcode]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.ProductModel?>>);

  @override
  _i5.Future<_i6.Result<List<_i7.ProductModel>>> getUserProducts(
    String? userId, {
    String? orderBy,
    String? sortBy,
    int? limit,
    int? offset,
    String? contains,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserProducts,
              [userId],
              {
                #orderBy: orderBy,
                #sortBy: sortBy,
                #limit: limit,
                #offset: offset,
                #contains: contains,
              },
            ),
            returnValue: _i5.Future<_i6.Result<List<_i7.ProductModel>>>.value(
              _i8.dummyValue<_i6.Result<List<_i7.ProductModel>>>(
                this,
                Invocation.method(
                  #getUserProducts,
                  [userId],
                  {
                    #orderBy: orderBy,
                    #sortBy: sortBy,
                    #limit: limit,
                    #offset: offset,
                    #contains: contains,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i6.Result<List<_i7.ProductModel>>>);

  @override
  _i5.Future<_i6.Result<void>> saveProductUnits(
    int? productId,
    List<_i9.ProductUnitModel>? units,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductUnits, [productId, units]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#saveProductUnits, [productId, units]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<List<_i9.ProductUnitModel>>> getProductUnits(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductUnits, [productId]),
            returnValue:
                _i5.Future<_i6.Result<List<_i9.ProductUnitModel>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i9.ProductUnitModel>>>(
                    this,
                    Invocation.method(#getProductUnits, [productId]),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i9.ProductUnitModel>>>);

  @override
  _i5.Future<_i6.Result<void>> deleteProductUnits(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductUnits, [productId]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteProductUnits, [productId]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);
}

/// A class which mocks [QueuedActionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueuedActionRepository extends _i1.Mock
    implements _i11.QueuedActionRepository {
  MockQueuedActionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<int>> createQueuedAction(
    _i12.QueuedActionEntity? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createQueuedAction, [action]),
            returnValue: _i5.Future<_i6.Result<int>>.value(
              _i8.dummyValue<_i6.Result<int>>(
                this,
                Invocation.method(#createQueuedAction, [action]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<int>>);

  @override
  _i5.Future<_i6.Result<List<_i12.QueuedActionEntity>>> getAllQueuedActions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllQueuedActions, []),
            returnValue:
                _i5.Future<_i6.Result<List<_i12.QueuedActionEntity>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i12.QueuedActionEntity>>>(
                    this,
                    Invocation.method(#getAllQueuedActions, []),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i12.QueuedActionEntity>>>);

  @override
  _i5.Future<_i6.Result<void>> deleteQueuedAction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteQueuedAction, [id]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteQueuedAction, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);
}
