// Mocks generated by Mockito 5.4.6 from annotations
// in mono_pos/test/data/repositories/transaction_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:mono_pos/core/common/result.dart' as _i6;
import 'package:mono_pos/core/services/sync/sync_service.dart' as _i2;
import 'package:mono_pos/data/datasources/interfaces/transaction_datasource.dart'
    as _i9;
import 'package:mono_pos/data/datasources/local/transaction_local_datasource_impl.dart'
    as _i4;
import 'package:mono_pos/data/models/transaction_model.dart' as _i7;
import 'package:mono_pos/domain/entities/queued_action_entity.dart' as _i11;
import 'package:mono_pos/domain/repositories/queued_action_repository.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i2.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SyncMode get mode =>
      (super.noSuchMethod(
            Invocation.getter(#mode),
            returnValue: _i2.SyncMode.auto,
          )
          as _i2.SyncMode);

  @override
  bool get forcedOffline =>
      (super.noSuchMethod(Invocation.getter(#forcedOffline), returnValue: false)
          as bool);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setMode(_i2.SyncMode? mode) => super.noSuchMethod(
    Invocation.method(#setMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleMode() => super.noSuchMethod(
    Invocation.method(#toggleMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TransactionLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionLocalDatasourceImpl extends _i1.Mock
    implements _i4.TransactionLocalDatasourceImpl {
  MockTransactionLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<int>> createTransaction(
    _i7.TransactionModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [transaction]),
            returnValue: _i5.Future<_i6.Result<int>>.value(
              _i8.dummyValue<_i6.Result<int>>(
                this,
                Invocation.method(#createTransaction, [transaction]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<int>>);

  @override
  _i5.Future<_i6.Result<void>> updateTransaction(
    _i7.TransactionModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#updateTransaction, [transaction]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<void>> updatePaymentStatus(
    int? id,
    String? status, {
    String? paymentQR,
    String? paymentExternalId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updatePaymentStatus,
              [id, status],
              {#paymentQR: paymentQR, #paymentExternalId: paymentExternalId},
            ),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(
                  #updatePaymentStatus,
                  [id, status],
                  {
                    #paymentQR: paymentQR,
                    #paymentExternalId: paymentExternalId,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<void>> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteTransaction, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<_i7.TransactionModel?>> getTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [id]),
            returnValue: _i5.Future<_i6.Result<_i7.TransactionModel?>>.value(
              _i8.dummyValue<_i6.Result<_i7.TransactionModel?>>(
                this,
                Invocation.method(#getTransaction, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.TransactionModel?>>);

  @override
  _i5.Future<_i6.Result<List<_i7.TransactionModel>>> getAllUserTransactions(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserTransactions, [userId]),
            returnValue:
                _i5.Future<_i6.Result<List<_i7.TransactionModel>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i7.TransactionModel>>>(
                    this,
                    Invocation.method(#getAllUserTransactions, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i7.TransactionModel>>>);

  @override
  _i5.Future<_i6.Result<List<_i7.TransactionModel>>> getTransactionsByDateRange(
    String? userId, {
    required String? startDate,
    required String? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTransactionsByDateRange,
              [userId],
              {#startDate: startDate, #endDate: endDate},
            ),
            returnValue:
                _i5.Future<_i6.Result<List<_i7.TransactionModel>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i7.TransactionModel>>>(
                    this,
                    Invocation.method(
                      #getTransactionsByDateRange,
                      [userId],
                      {#startDate: startDate, #endDate: endDate},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i7.TransactionModel>>>);

  @override
  _i5.Future<_i6.Result<List<_i7.TransactionModel>>> getUserTransactions(
    String? userId, {
    String? orderBy = 'createdAt',
    String? sortBy = 'DESC',
    int? limit = 10,
    int? offset,
    String? contains,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserTransactions,
              [userId],
              {
                #orderBy: orderBy,
                #sortBy: sortBy,
                #limit: limit,
                #offset: offset,
                #contains: contains,
              },
            ),
            returnValue:
                _i5.Future<_i6.Result<List<_i7.TransactionModel>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i7.TransactionModel>>>(
                    this,
                    Invocation.method(
                      #getUserTransactions,
                      [userId],
                      {
                        #orderBy: orderBy,
                        #sortBy: sortBy,
                        #limit: limit,
                        #offset: offset,
                        #contains: contains,
                      },
                    ),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i7.TransactionModel>>>);
}

/// A class which mocks [TransactionDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionDatasource extends _i1.Mock
    implements _i9.TransactionDatasource {
  MockTransactionDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<int>> createTransaction(
    _i7.TransactionModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [transaction]),
            returnValue: _i5.Future<_i6.Result<int>>.value(
              _i8.dummyValue<_i6.Result<int>>(
                this,
                Invocation.method(#createTransaction, [transaction]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<int>>);

  @override
  _i5.Future<_i6.Result<void>> updateTransaction(
    _i7.TransactionModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [transaction]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#updateTransaction, [transaction]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<void>> updatePaymentStatus(
    int? id,
    String? status, {
    String? paymentQR,
    String? paymentExternalId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updatePaymentStatus,
              [id, status],
              {#paymentQR: paymentQR, #paymentExternalId: paymentExternalId},
            ),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(
                  #updatePaymentStatus,
                  [id, status],
                  {
                    #paymentQR: paymentQR,
                    #paymentExternalId: paymentExternalId,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<void>> deleteTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteTransaction, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<_i7.TransactionModel?>> getTransaction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [id]),
            returnValue: _i5.Future<_i6.Result<_i7.TransactionModel?>>.value(
              _i8.dummyValue<_i6.Result<_i7.TransactionModel?>>(
                this,
                Invocation.method(#getTransaction, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.TransactionModel?>>);

  @override
  _i5.Future<_i6.Result<List<_i7.TransactionModel>>> getAllUserTransactions(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserTransactions, [userId]),
            returnValue:
                _i5.Future<_i6.Result<List<_i7.TransactionModel>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i7.TransactionModel>>>(
                    this,
                    Invocation.method(#getAllUserTransactions, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i7.TransactionModel>>>);

  @override
  _i5.Future<_i6.Result<List<_i7.TransactionModel>>> getUserTransactions(
    String? userId, {
    String? orderBy,
    String? sortBy,
    int? limit,
    int? offset,
    String? contains,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserTransactions,
              [userId],
              {
                #orderBy: orderBy,
                #sortBy: sortBy,
                #limit: limit,
                #offset: offset,
                #contains: contains,
              },
            ),
            returnValue:
                _i5.Future<_i6.Result<List<_i7.TransactionModel>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i7.TransactionModel>>>(
                    this,
                    Invocation.method(
                      #getUserTransactions,
                      [userId],
                      {
                        #orderBy: orderBy,
                        #sortBy: sortBy,
                        #limit: limit,
                        #offset: offset,
                        #contains: contains,
                      },
                    ),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i7.TransactionModel>>>);

  @override
  _i5.Future<_i6.Result<List<_i7.TransactionModel>>> getTransactionsByDateRange(
    String? userId, {
    required String? startDate,
    required String? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTransactionsByDateRange,
              [userId],
              {#startDate: startDate, #endDate: endDate},
            ),
            returnValue:
                _i5.Future<_i6.Result<List<_i7.TransactionModel>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i7.TransactionModel>>>(
                    this,
                    Invocation.method(
                      #getTransactionsByDateRange,
                      [userId],
                      {#startDate: startDate, #endDate: endDate},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i7.TransactionModel>>>);
}

/// A class which mocks [QueuedActionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueuedActionRepository extends _i1.Mock
    implements _i10.QueuedActionRepository {
  MockQueuedActionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<int>> createQueuedAction(
    _i11.QueuedActionEntity? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createQueuedAction, [action]),
            returnValue: _i5.Future<_i6.Result<int>>.value(
              _i8.dummyValue<_i6.Result<int>>(
                this,
                Invocation.method(#createQueuedAction, [action]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<int>>);

  @override
  _i5.Future<_i6.Result<List<_i11.QueuedActionEntity>>> getAllQueuedActions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllQueuedActions, []),
            returnValue:
                _i5.Future<_i6.Result<List<_i11.QueuedActionEntity>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i11.QueuedActionEntity>>>(
                    this,
                    Invocation.method(#getAllQueuedActions, []),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i11.QueuedActionEntity>>>);

  @override
  _i5.Future<_i6.Result<void>> deleteQueuedAction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteQueuedAction, [id]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteQueuedAction, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);
}
