// Mocks generated by Mockito 5.4.6 from annotations
// in mono_pos/test/data/repositories/user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:mono_pos/core/common/result.dart' as _i6;
import 'package:mono_pos/core/services/sync/sync_service.dart' as _i2;
import 'package:mono_pos/data/datasources/interfaces/user_datasource.dart'
    as _i9;
import 'package:mono_pos/data/datasources/local/user_local_datasource_impl.dart'
    as _i4;
import 'package:mono_pos/data/models/user_model.dart' as _i7;
import 'package:mono_pos/domain/entities/queued_action_entity.dart' as _i11;
import 'package:mono_pos/domain/repositories/queued_action_repository.dart'
    as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i2.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SyncMode get mode =>
      (super.noSuchMethod(
            Invocation.getter(#mode),
            returnValue: _i2.SyncMode.auto,
          )
          as _i2.SyncMode);

  @override
  bool get forcedOffline =>
      (super.noSuchMethod(Invocation.getter(#forcedOffline), returnValue: false)
          as bool);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setMode(_i2.SyncMode? mode) => super.noSuchMethod(
    Invocation.method(#setMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleMode() => super.noSuchMethod(
    Invocation.method(#toggleMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDatasourceImpl extends _i1.Mock
    implements _i4.UserLocalDatasourceImpl {
  MockUserLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<String>> createUser(_i7.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i5.Future<_i6.Result<String>>.value(
              _i8.dummyValue<_i6.Result<String>>(
                this,
                Invocation.method(#createUser, [user]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<String>>);

  @override
  _i5.Future<_i6.Result<void>> updateUser(_i7.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<void>> deleteUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteUser, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<_i7.UserModel?>> getUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [id]),
            returnValue: _i5.Future<_i6.Result<_i7.UserModel?>>.value(
              _i8.dummyValue<_i6.Result<_i7.UserModel?>>(
                this,
                Invocation.method(#getUser, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.UserModel?>>);

  @override
  _i5.Future<_i6.Result<List<_i7.UserModel>>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i5.Future<_i6.Result<List<_i7.UserModel>>>.value(
              _i8.dummyValue<_i6.Result<List<_i7.UserModel>>>(
                this,
                Invocation.method(#getAllUsers, []),
              ),
            ),
          )
          as _i5.Future<_i6.Result<List<_i7.UserModel>>>);

  @override
  _i5.Future<_i6.Result<_i7.UserModel?>> getUserByUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUsername, [username]),
            returnValue: _i5.Future<_i6.Result<_i7.UserModel?>>.value(
              _i8.dummyValue<_i6.Result<_i7.UserModel?>>(
                this,
                Invocation.method(#getUserByUsername, [username]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.UserModel?>>);
}

/// A class which mocks [UserDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDatasource extends _i1.Mock implements _i9.UserDatasource {
  MockUserDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<String>> createUser(_i7.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i5.Future<_i6.Result<String>>.value(
              _i8.dummyValue<_i6.Result<String>>(
                this,
                Invocation.method(#createUser, [user]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<String>>);

  @override
  _i5.Future<_i6.Result<void>> updateUser(_i7.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<void>> deleteUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [id]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteUser, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);

  @override
  _i5.Future<_i6.Result<_i7.UserModel?>> getUser(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [id]),
            returnValue: _i5.Future<_i6.Result<_i7.UserModel?>>.value(
              _i8.dummyValue<_i6.Result<_i7.UserModel?>>(
                this,
                Invocation.method(#getUser, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.UserModel?>>);

  @override
  _i5.Future<_i6.Result<_i7.UserModel?>> getUserByUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUsername, [username]),
            returnValue: _i5.Future<_i6.Result<_i7.UserModel?>>.value(
              _i8.dummyValue<_i6.Result<_i7.UserModel?>>(
                this,
                Invocation.method(#getUserByUsername, [username]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<_i7.UserModel?>>);

  @override
  _i5.Future<_i6.Result<List<_i7.UserModel>>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i5.Future<_i6.Result<List<_i7.UserModel>>>.value(
              _i8.dummyValue<_i6.Result<List<_i7.UserModel>>>(
                this,
                Invocation.method(#getAllUsers, []),
              ),
            ),
          )
          as _i5.Future<_i6.Result<List<_i7.UserModel>>>);
}

/// A class which mocks [QueuedActionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueuedActionRepository extends _i1.Mock
    implements _i10.QueuedActionRepository {
  MockQueuedActionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<int>> createQueuedAction(
    _i11.QueuedActionEntity? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createQueuedAction, [action]),
            returnValue: _i5.Future<_i6.Result<int>>.value(
              _i8.dummyValue<_i6.Result<int>>(
                this,
                Invocation.method(#createQueuedAction, [action]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<int>>);

  @override
  _i5.Future<_i6.Result<List<_i11.QueuedActionEntity>>> getAllQueuedActions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllQueuedActions, []),
            returnValue:
                _i5.Future<_i6.Result<List<_i11.QueuedActionEntity>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i11.QueuedActionEntity>>>(
                    this,
                    Invocation.method(#getAllQueuedActions, []),
                  ),
                ),
          )
          as _i5.Future<_i6.Result<List<_i11.QueuedActionEntity>>>);

  @override
  _i5.Future<_i6.Result<void>> deleteQueuedAction(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteQueuedAction, [id]),
            returnValue: _i5.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(#deleteQueuedAction, [id]),
              ),
            ),
          )
          as _i5.Future<_i6.Result<void>>);
}
