// Mocks generated by Mockito 5.4.6 from annotations
// in mono_pos/test/domain/usecases/product_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:mono_pos/core/common/result.dart' as _i4;
import 'package:mono_pos/domain/entities/product_entity.dart' as _i5;
import 'package:mono_pos/domain/entities/product_tier_entity.dart' as _i8;
import 'package:mono_pos/domain/entities/product_unit_entity.dart' as _i7;
import 'package:mono_pos/domain/repositories/product_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i2.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.ProductEntity?>> getProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [productId]),
            returnValue: _i3.Future<_i4.Result<_i5.ProductEntity?>>.value(
              _i6.dummyValue<_i4.Result<_i5.ProductEntity?>>(
                this,
                Invocation.method(#getProduct, [productId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.ProductEntity?>>);

  @override
  _i3.Future<_i4.Result<_i5.ProductEntity?>> getProductByBarcode(
    String? barcode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductByBarcode, [barcode]),
            returnValue: _i3.Future<_i4.Result<_i5.ProductEntity?>>.value(
              _i6.dummyValue<_i4.Result<_i5.ProductEntity?>>(
                this,
                Invocation.method(#getProductByBarcode, [barcode]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.ProductEntity?>>);

  @override
  _i3.Future<_i4.Result<int>> createProduct(_i5.ProductEntity? product) =>
      (super.noSuchMethod(
            Invocation.method(#createProduct, [product]),
            returnValue: _i3.Future<_i4.Result<int>>.value(
              _i6.dummyValue<_i4.Result<int>>(
                this,
                Invocation.method(#createProduct, [product]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<int>>);

  @override
  _i3.Future<_i4.Result<void>> updateProduct(_i5.ProductEntity? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateProduct, [product]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteProduct, [productId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i5.ProductEntity>>> getUserProducts(
    String? userId, {
    String? orderBy,
    String? sortBy,
    int? limit,
    int? offset,
    String? contains,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserProducts,
              [userId],
              {
                #orderBy: orderBy,
                #sortBy: sortBy,
                #limit: limit,
                #offset: offset,
                #contains: contains,
              },
            ),
            returnValue: _i3.Future<_i4.Result<List<_i5.ProductEntity>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.ProductEntity>>>(
                this,
                Invocation.method(
                  #getUserProducts,
                  [userId],
                  {
                    #orderBy: orderBy,
                    #sortBy: sortBy,
                    #limit: limit,
                    #offset: offset,
                    #contains: contains,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.ProductEntity>>>);

  @override
  _i3.Future<_i4.Result<List<_i7.ProductUnitEntity>>> getProductUnits(
    int? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductUnits, [productId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i7.ProductUnitEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i7.ProductUnitEntity>>>(
                    this,
                    Invocation.method(#getProductUnits, [productId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i7.ProductUnitEntity>>>);

  @override
  _i3.Future<_i4.Result<void>> saveProductUnits(
    int? productId,
    List<_i7.ProductUnitEntity>? units,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductUnits, [productId, units]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveProductUnits, [productId, units]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i5.ProductEntity>>> getLowStockProducts(
    String? userId,
    int? threshold,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLowStockProducts, [userId, threshold]),
            returnValue: _i3.Future<_i4.Result<List<_i5.ProductEntity>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.ProductEntity>>>(
                this,
                Invocation.method(#getLowStockProducts, [userId, threshold]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.ProductEntity>>>);

  @override
  _i3.Future<_i4.Result<List<_i8.ProductTierEntity>>> getProductTiers(
    int? productUnitId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductTiers, [productUnitId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i8.ProductTierEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i8.ProductTierEntity>>>(
                    this,
                    Invocation.method(#getProductTiers, [productUnitId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i8.ProductTierEntity>>>);

  @override
  _i3.Future<_i4.Result<void>> saveProductTiers(
    int? productUnitId,
    List<_i8.ProductTierEntity>? tiers,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveProductTiers, [productUnitId, tiers]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveProductTiers, [productUnitId, tiers]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
